definitions:
  model.PostTodo:
    properties:
      description:
        type: string
      dueDate:
        type: string
      priority:
        type: integer
    type: object
  model.Todo:
    properties:
      description:
        type: string
      done:
        type: boolean
      dueDate:
        type: string
      id:
        type: integer
      priority:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: kuepper.alexander@web.de
    name: Alexander Kuepper
  description: With this API you can save Todos.
  title: Todo List API
  version: "1.0"
paths:
  /todo:
    get:
      consumes:
      - application/json
      description: get all Todos
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
        "500":
          description: Server Error
      summary: Show all todos
      tags:
      - todo
    post:
      consumes:
      - application/json
      description: you can create a todo with this method
      parameters:
      - description: todo
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.PostTodo'
      produces:
      - application/json
      responses:
        "201":
          description: Status Created
        "400":
          description: Not Found
      summary: Create a todo
      tags:
      - todo
  /todo/{id}:
    delete:
      description: everyone can delete the todo
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete the todo
      tags:
      - todo
    get:
      consumes:
      - application/json
      description: get todo by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
        "404":
          description: Not Found
        "500":
          description: Server Error
      summary: Show a todo
      tags:
      - todo
    patch:
      description: with this method you can set the done bit true
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Set todo done
      tags:
      - todo
swagger: "2.0"
